onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma

minimumReleaseAge: 10080

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msw: true
  prisma: true
  unrs-resolver: true
