/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthPagesRouteRouteImport } from './routes/_auth-pages/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBoardRouteImport } from './routes/_authenticated/board'
import { Route as AuthPagesSignupRouteImport } from './routes/_auth-pages/signup'
import { Route as AuthPagesResetPasswordRouteImport } from './routes/_auth-pages/reset-password'
import { Route as AuthPagesLoginRouteImport } from './routes/_auth-pages/login'
import { Route as AuthPagesEmailConfirmationRouteImport } from './routes/_auth-pages/email-confirmation'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthPagesRouteRoute = AuthPagesRouteRouteImport.update({
  id: '/_auth-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBoardRoute = AuthenticatedBoardRouteImport.update({
  id: '/_authenticated/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPagesSignupRoute = AuthPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthPagesRouteRoute,
} as any)
const AuthPagesResetPasswordRoute = AuthPagesResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthPagesRouteRoute,
} as any)
const AuthPagesLoginRoute = AuthPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthPagesRouteRoute,
} as any)
const AuthPagesEmailConfirmationRoute =
  AuthPagesEmailConfirmationRouteImport.update({
    id: '/email-confirmation',
    path: '/email-confirmation',
    getParentRoute: () => AuthPagesRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-confirmation': typeof AuthPagesEmailConfirmationRoute
  '/login': typeof AuthPagesLoginRoute
  '/reset-password': typeof AuthPagesResetPasswordRoute
  '/signup': typeof AuthPagesSignupRoute
  '/board': typeof AuthenticatedBoardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-confirmation': typeof AuthPagesEmailConfirmationRoute
  '/login': typeof AuthPagesLoginRoute
  '/reset-password': typeof AuthPagesResetPasswordRoute
  '/signup': typeof AuthPagesSignupRoute
  '/board': typeof AuthenticatedBoardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth-pages': typeof AuthPagesRouteRouteWithChildren
  '/_auth-pages/email-confirmation': typeof AuthPagesEmailConfirmationRoute
  '/_auth-pages/login': typeof AuthPagesLoginRoute
  '/_auth-pages/reset-password': typeof AuthPagesResetPasswordRoute
  '/_auth-pages/signup': typeof AuthPagesSignupRoute
  '/_authenticated/board': typeof AuthenticatedBoardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-confirmation'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/board'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-confirmation'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/board'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_auth-pages'
    | '/_auth-pages/email-confirmation'
    | '/_auth-pages/login'
    | '/_auth-pages/reset-password'
    | '/_auth-pages/signup'
    | '/_authenticated/board'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthPagesRouteRoute: typeof AuthPagesRouteRouteWithChildren
  AuthenticatedBoardRoute: typeof AuthenticatedBoardRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-pages': {
      id: '/_auth-pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/board': {
      id: '/_authenticated/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthenticatedBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-pages/signup': {
      id: '/_auth-pages/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthPagesSignupRouteImport
      parentRoute: typeof AuthPagesRouteRoute
    }
    '/_auth-pages/reset-password': {
      id: '/_auth-pages/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthPagesResetPasswordRouteImport
      parentRoute: typeof AuthPagesRouteRoute
    }
    '/_auth-pages/login': {
      id: '/_auth-pages/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthPagesLoginRouteImport
      parentRoute: typeof AuthPagesRouteRoute
    }
    '/_auth-pages/email-confirmation': {
      id: '/_auth-pages/email-confirmation'
      path: '/email-confirmation'
      fullPath: '/email-confirmation'
      preLoaderRoute: typeof AuthPagesEmailConfirmationRouteImport
      parentRoute: typeof AuthPagesRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthPagesRouteRouteChildren {
  AuthPagesEmailConfirmationRoute: typeof AuthPagesEmailConfirmationRoute
  AuthPagesLoginRoute: typeof AuthPagesLoginRoute
  AuthPagesResetPasswordRoute: typeof AuthPagesResetPasswordRoute
  AuthPagesSignupRoute: typeof AuthPagesSignupRoute
}

const AuthPagesRouteRouteChildren: AuthPagesRouteRouteChildren = {
  AuthPagesEmailConfirmationRoute: AuthPagesEmailConfirmationRoute,
  AuthPagesLoginRoute: AuthPagesLoginRoute,
  AuthPagesResetPasswordRoute: AuthPagesResetPasswordRoute,
  AuthPagesSignupRoute: AuthPagesSignupRoute,
}

const AuthPagesRouteRouteWithChildren = AuthPagesRouteRoute._addFileChildren(
  AuthPagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthPagesRouteRoute: AuthPagesRouteRouteWithChildren,
  AuthenticatedBoardRoute: AuthenticatedBoardRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
